### ISSUE TITLE
n_trees in example vs n_tress in survival

### ISSUE THREAD

**Issue by nsasanka** [Wrymm/Random-Survival-Forests#5]
if I want say n_trees=3000 should I change example.py n_tree only

rd = RandomSurvivalForest(n_trees=3000)

 or both example.py n_tree and survival.py n_tree?

rd = RandomSurvivalForest(n_trees=3000) and

def __init__(self, n_trees = 3000, max_features = 2, max_depth = 5, min_samples_split = 2, split = "auto"):

**Comment by Wrymm** [comment]
Hi,
No need to edit the function, just do :
rd = RandomSurvivalForest(n_trees=3000)
